
window.physiologyData = {
  cns: {
    title: "CNS (Central Nervous System)",
    questions: [
      { q: "Which part of the brain is responsible for coordination, balance, and motor control?", type: "mcq", options: ["Cerebrum", "Cerebellum", "Brainstem", "Thalamus"], a: 1, hint: "المخيخ (Cerebellum) هو المسؤول عن 'تناسق' الحركة والتوازن." },
      { q: "Which lobe of the cerebrum is primarily responsible for vision?", type: "mcq", options: ["Frontal", "Parietal", "Temporal", "Occipital"], a: 3, hint: "الفص 'القفوي' (Occipital) الموجود في الجزء الخلفي من الدماغ يعالج الرؤية." },
      { q: "Which lobe is responsible for hearing, memory, and language comprehension (Wernicke's area)?", type: "mcq", options: ["Frontal", "Parietal", "Temporal", "Occipital"], a: 2, hint: "الفص 'الصدغي' (Temporal) الموجود على جانبي الرأس (بالقرب من الأذنين)." },
      { q: "Which lobe is responsible for voluntary movement (motor cortex) and higher executive functions?", type: "mcq", options: ["Frontal", "Parietal", "Temporal", "Occipital"], a: 0, hint: "الفص 'الجبهي' (Frontal) هو مركز التخطيط، واتخاذ القرار، والحركة الإرادية." },
      { q: "Which lobe processes sensory information like touch, temperature, and pain (somatosensory cortex)?", type: "mcq", options: ["Frontal", "Parietal", "Temporal", "Occipital"], a: 1, hint: "الفص 'الجداري' (Parietal) هو المركز الحسي الرئيسي للجسم." },
      { q: "The 'relay station' for most sensory information coming into the cortex is the:", type: "mcq", options: ["Hypothalamus", "Thalamus", "Cerebellum", "Medulla"], a: 1, hint: "المهاد (Thalamus) هو 'سكرتير' الدماغ الذي يوجه الإشارات الحسية (ما عدا الشم) إلى القشرة." },
      { q: "Which structure regulates homeostasis, temperature, hunger, and the endocrine system?", type: "mcq", options: ["Hypothalamus", "Thalamus", "Cerebellum", "Pons"], a: 0, hint: "تحت المهاد (Hypothalamus) هو 'منظم الحرارة' ومركز التحكم في التوازن الداخلي للجسم." },
      { q: "Which part of the brainstem controls vital functions like breathing and heart rate?", type: "mcq", options: ["Midbrain", "Pons", "Medulla oblongata", "Cerebellum"], a: 2, hint: "النخاع المستطيل (Medulla) هو المركز الحيوي الأساسي، وأي إصابة فيه مميتة." },
      { q: "The system responsible for emotion, learning, and memory (includes hippocampus and amygdala) is the:", type: "mcq", options: ["Reticular formation", "Limbic system", "Endocrine system", "Basal ganglia"], a: 1, hint: "الجهاز 'الحوفي' (Limbic System) هو 'دماغ المشاعر'." },
      { q: "The 'master gland' of the endocrine system, controlled by the hypothalamus, is the:", type: "mcq", options: ["Pineal gland", "Adrenal gland", "Thyroid gland", "Pituitary gland"], a: 3, hint: "الغدة 'النخامية' (Pituitary) تفرز هرمونات تتحكم في جميع الغدد الأخرى." },
      { q: "The fluid that surrounds and protects the brain and spinal cord is:", type: "mcq", options: ["Blood plasma", "Cerebrospinal fluid (CSF)", "Lymph", "Synovial fluid"], a: 1, hint: "السائل 'الدماغي الشوكي' (CSF) يعمل كوسادة لحماية الجهاز العصبي المركزي." },
      { q: "The 'fight or flight' response is controlled by the:", type: "mcq", options: ["Sympathetic nervous system", "Parasympathetic nervous system", "Somatic nervous system", "Enteric nervous system"], a: 0, hint: "الجهاز 'الودي' (Sympathetic) هو المسؤول عن الاستجابة للضغط والخطر." },
      { q: "The 'rest and digest' response is controlled by the:", type: "mcq", options: ["Sympathetic nervous system", "Parasympathetic nervous system", "Somatic nervous system", "Afferent division"], a: 1, hint: "الجهاز 'اللاودي' (Parasympathetic) هو المسؤول عن الهدوء والهضم." },
      { q: "The primary neurotransmitter of the parasympathetic nervous system is:", type: "mcq", options: ["Norepinephrine", "Acetylcholine", "Dopamine", "Serotonin"], a: 1, hint: "هو نفس الناقل المستخدم في الموصل العصبي العضلي." },
      { q: "Broca's area, responsible for speech production, is located in which lobe?", type: "mcq", options: ["Frontal", "Parietal", "Temporal", "Occipital"], a: 0, hint: "تقع في الفص الجبهي، وإصابتها تؤدي إلى صعوبة في 'إنتاج' الكلام وليس فهمه." }
    ]
  },
  blood: {
    title: "Blood",
    questions: [
      { q: "Which component makes up the largest percentage of blood volume?", type: "mcq", options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], a: 3, hint: "البلازما هي السائل الأصفر الذي تسبح فيه الخلايا (أكثر من 50%)." },
      { q: "What is the primary function of Red Blood Cells (Erythrocytes)?", type: "mcq", options: ["Fight infection", "Transport oxygen", "Blood clotting", "Produce antibodies"], a: 1, hint: "تحتوي على الهيموجلوبين الذي يرتبط بالأكسجين." },
      { q: "What is the name of the protein in RBCs that binds to oxygen?", type: "mcq", options: ["Albumin", "Globulin", "Hemoglobin", "Fibrinogen"], a: 2, hint: "هذا البروتين يحتوي على الحديد ويعطي الدم لونه الأحمر." },
      { q: "Which of the following is NOT a type of White Blood Cell (Leukocyte)?", type: "mcq", options: ["Neutrophil", "Lymphocyte", "Erythrocyte", "Monocyte"], a: 2, hint: "Erythrocyte هو اسم آخر لكرات الدم الحمراء." },
      { q: "Which WBC is the most abundant and is the 'first responder' to bacterial infections?", type: "mcq", options: ["Neutrophil", "Eosinophil", "Basophil", "Lymphocyte"], a: 0, hint: "الخلايا 'العدلة' (Neutrophils) هي خط الدفاع الأول وتزداد أعدادها بشكل كبير في العدوى البكتيرية." },
      { q: "Which WBC is involved in allergic reactions and fighting parasitic infections?", type: "mcq", options: ["Neutrophil", "Eosinophil", "Basophil", "Monocyte"], a: 1, hint: "الخلايا 'الحمضية' (Eosinophils) تزداد في حالات الحساسية والديدان." },
      { q: "Which WBC releases histamine during inflammation and allergic reactions?", type: "mcq", options: ["Neutrophil", "Eosinophil", "Basophil", "Lymphocyte"], a: 2, hint: "الخلايا 'القاعدية' (Basophils) (و الخلايا البدينة) هي مخازن الهيستامين." },
      { q: "Which WBCs are responsible for specific immunity (B-cells and T-cells)?", type: "mcq", options: ["Neutrophils", "Monocytes", "Basophils", "Lymphocytes"], a: 3, hint: "الخلايا 'اللمفاوية' (Lymphocytes) هي المسؤولة عن الذاكرة المناعية وإنتاج الأجسام المضادة." },
      { q: "Which cell becomes a macrophage when it leaves the bloodstream and enters tissues?", type: "mcq", options: ["Neutrophil", "Eosinophil", "Monocyte", "B-cell"], a: 2, hint: "الخلية 'الوحيدة' (Monocyte) في الدم تتحول إلى خلية 'أكولة كبيرة' (Macrophage) في الأنسجة." },
      { q: "What is the function of Platelets (Thrombocytes)?", type: "mcq", options: ["Oxygen transport", "Immune defense", "Blood clotting (Hemostasis)", "Carry nutrients"], a: 2, hint: "الصفائح الدموية هي المسؤولة عن تكوين الجلطة الأولية لسد الجروح." },
      { q: "What is the name of the process of blood cell formation?", type: "mcq", options: ["Hemostasis", "Erythropoiesis", "Hematopoiesis", "Phagocytosis"], a: 2, hint: "كلمة 'Poiesis' تعني 'تكوين'، و 'Hemato' تعني 'دم'." },
      { q: "Where does hematopoiesis (blood cell formation) occur in adults?", type: "mcq", options: ["Liver", "Spleen", "Yellow bone marrow", "Red bone marrow"], a: 3, hint: "في نخاع العظم 'الأحمر' (الموجود في العظام المسطحة)." },
      { q: "A person with Type A blood has which antibodies in their plasma?", type: "mcq", options: ["Anti-A antibodies", "Anti-B antibodies", "Both Anti-A and Anti-B", "No antibodies"], a: 1, hint: "لديك أجسام مضادة (Anti) للنوع الذي 'لا' تملكه." },
      { q: "A person with Type O blood can receive blood from:", type: "mcq", options: ["Type A only", "Type B only", "Type AB only", "Type O only"], a: 3, hint: "فصيلة O لديها أجسام مضادة Anti-A و Anti-B، لذا لا يمكنها استقبال سوى فصيلة O." },
      { q: "The 'Universal Donor' blood type is:", type: "mcq", options: ["A+", "B-", "AB+", "O-"], a: 3, hint: "المعطي 'العام' هو O سالب، لأنه لا يحتوي على أي مستضدات (A, B, أو Rh)." }
    ]
  },
  cvs: {
    title: "CVS (Cardiovascular System)",
    questions: [
      { q: "What is Cardiac Output (CO)?", type: "mcq", options: ["Heart Rate x Stroke Volume", "Systolic BP - Diastolic BP", "Blood flow per minute", "Both A and C"], a: 3, hint: "النتاج القلبي (CO) هو كمية الدم التي يضخها القلب في دقيقة واحدة." },
      { q: "What is Stroke Volume (SV)?", type: "mcq", options: ["Blood ejected per minute", "Blood ejected per beat", "Heart rate in beats/min", "Pressure in the aorta"], a: 1, hint: "حجم 'الدفقة' (Stroke Volume) هو كمية الدم التي يضخها القلب في 'النبضة' الواحدة." },
      { q: "The Frank-Starling Law of the heart states that:", type: "mcq", options: ["Increased heart rate increases CO", "Increased preload (EDV) leads to increased stroke volume", "Increased afterload decreases stroke volume", "Parasympathetic stimulation slows the heart"], a: 1, hint: "كلما امتلأ القلب بالدم أكثر (زيادة التمدد)، كلما انقبض بقوة أكبر." },
      { q: "What is 'preload'?", type: "mcq", options: ["The pressure the heart must pump against", "The volume of blood in the ventricle at end-diastole", "The contractility of the heart muscle", "The heart rate"], a: 1, hint: "'الحمل القبلي' (Preload) هو حجم الدم (التمدد) الذي يواجهه القلب 'قبل' الانقباض." },
      { q: "What is 'afterload'?", type: "mcq", options: ["The pressure the heart must pump against (e.g., aortic pressure)", "The volume of blood in the ventricle", "The contractility of the heart", "The heart rate"], a: 0, hint: "'الحمل البعدي' (Afterload) هو المقاومة (الضغط) التي يجب على القلب التغلب عليها 'بعد' بدء الانقباض." },
      { q: "Systolic blood pressure represents:", type: "mcq", options: ["Pressure in the arteries during ventricular relaxation", "Pressure in the arteries during ventricular contraction", "The average pressure in the arteries", "The pressure in the veins"], a: 1, hint: "الضغط 'الانقباضي' (Systolic) هو الرقم 'الأعلى'، ويمثل الضغط أثناء انقباض القلب." },
      { q: "Diastolic blood pressure represents:", type: "mcq", options: ["Pressure in the arteries during ventricular relaxation", "Pressure in the arteries during ventricular contraction", "The average pressure in the arteries", "The pressure in the atria"], a: 0, hint: "الضغط 'الانبساطي' (Diastolic) هو الرقم 'الأدنى'، ويمثل الضغط أثناء انبساط (راحة) القلب." },
      { q: "Pulse Pressure is:", type: "mcq", options: ["Systolic + Diastolic", "Systolic - Diastolic", "(Systolic + 2*Diastolic) / 3", "Heart Rate x Stroke Volume"], a: 1, hint: "ضغط النبض هو 'الفرق' بين الضغط الانقباضي والانبساطي." },
      { q: "Mean Arterial Pressure (MAP) is approximately:", type: "mcq", options: ["Systolic - Diastolic", "Diastolic + 1/3 (Pulse Pressure)", "Heart Rate x Stroke Volume", "Systolic + Diastolic / 2"], a: 1, hint: "متوسط ضغط الشرايين (MAP) هو ليس مجرد المتوسط الحسابي، لأنه يقضي وقتاً أطول في الانبساط." },
      { q: "Where is blood pressure the lowest in the cardiovascular system?", type: "mcq", options: ["Aorta", "Arterioles", "Capillaries", "Large Veins (Vena Cava)"], a: 3, hint: "الضغط يكون الأعلى عند الخروج من القلب (الأورطي) والأدنى عند العودة إليه (الأوردة الكبيرة)." },
      { q: "Which vessels are the primary site of peripheral resistance (regulating BP)?", type: "mcq", options: ["Aorta", "Arterioles", "Capillaries", "Veins"], a: 1, hint: "الشُرينات (Arterioles) هي 'صمامات' التحكم الرئيسية التي يمكن أن تتوسع أو تضيق لتنظيم المقاومة." },
      { q: "The baroreceptor reflex (for short-term BP control) is located in the:", type: "mcq", options: ["Carotid sinus and Aortic arch", "Kidneys", "Brain (Hypothalamus)", "Adrenal glands"], a: 0, hint: "مستقبلات 'الضغط' (Baroreceptors) موجودة في القوس الأبهري والشريان السباتي لمراقبة الضغط." },
      { q: "If baroreceptors detect high blood pressure, what is the reflex response?", type: "mcq", options: ["Increase heart rate, Vasoconstriction", "Decrease heart rate, Vasodilation", "Increase heart rate, Vasodilation", "Decrease heart rate, Vasoconstriction"], a: 1, hint: "إذا كان الضغط مرتفعاً، يستجيب الجسم بـ 'تهدئة' الأمور (خفض معدل القلب وتوسيع الأوعية)." },
      { q: "Which hormone system is the primary long-term regulator of blood pressure (via blood volume)?", type: "mcq", options: ["Baroreceptor reflex", "Renin-Angiotensin-Aldosterone System (RAAS)", "Sympathetic nervous system", "Epinephrine release"], a: 1, hint: "نظام (RAAS) يتحكم في ضغط الدم على المدى الطويل عن طريق الكلى (الاحتفاظ بالصوديوم والماء)." },
      { q: "What is the main factor that causes blood to return to the heart from the veins (venous return)?", type: "mcq", options: ["High pressure in the veins", "Skeletal muscle pump and Respiratory pump", "Strong contractions of the atria", "Heart suction"], a: 1, hint: "الضغط في الأوردة منخفض جداً، لذا يعتمد العائد الوريدي على 'مضخة' العضلات و 'مضخة' التنفس." }
    ]
  }
};
